service: lambda-todo-api

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:432754786374:table/MyTable

functions:
  addTodo:
    handler: build/addTodo.handler
    events:
      - http:
          path: /
          method: post
  fetchTodos:
    handler: build/fetchTodos.handler
    events:
      - http:
          path: /get-all-todos
          method: get
  deleteTodo:
    handler: build/deleteTodo.handler
    events:
      - http:
          path: /deleteTodo/{id}
          method: delete
resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MyTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
